# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from apitax.api.models.base_model_ import Model
from apitax.api.models.user import User  # noqa: F401,E501
from apitax.api import util


class UserSave(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, script=None):  # noqa: E501
        """UserSave - a model defined in Swagger

        :param script: The script of this UserSave.  # noqa: E501
        :type script: User
        """
        self.swagger_types = {
            'script': User
        }

        self.attribute_map = {
            'script': 'script'
        }

        self._script = script

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_save of this UserSave.  # noqa: E501
        :rtype: UserSave
        """
        return util.deserialize_model(dikt, cls)

    @property
    def script(self):
        """Gets the script of this UserSave.


        :return: The script of this UserSave.
        :rtype: User
        """
        return self._script

    @script.setter
    def script(self, script):
        """Sets the script of this UserSave.


        :param script: The script of this UserSave.
        :type script: User
        """
        if script is None:
            raise ValueError("Invalid value for `script`, must not be `None`")  # noqa: E501

        self._script = script
